### ISSUE TITLE
Scenario #115 would not draw round 2

### ISSUE THREAD

**Issue by madjayem** [Tarmslitaren/FrosthavenAssistant#9] opened 2022-10-09 13:52 UTC
Playing with four players over local network. We got to inputting initiative for round 2, but when I hit the Draw button nothing happened. We could not progress the scenario.

**Comment by Tarmslitaren** [comment] 2022-10-11 06:13
seems to be specific to scenario 115 (congrats on getting to the end boss by the way) and reproducible also without network.

found same issue in Crimson Scales #53 , note solo and sun solo scenarios. will be fixed in next version (likely hotfix)

cause: monsters with only one ability card needs to have the card marked to be 'shuffled' back into deck or it blocks progress.

**Comment by Tarmslitaren** [comment] 2022-10-20 20:13
fixed in 1.3.0

**Closed by Tarmslitaren** 2022-10-20 20:13 UTC
