### ISSUE TITLE
Under the Ice Scenario Rule Bug

### ISSUE THREAD

**Issue by salesforce-john** [Tarmslitaren/FrosthavenAssistant#204] opened 2023-11-12 16:19 UTC
Special Rules indicate additional enemies don't spawn until after the Steel Automaton is killed.

Current functionality has them summoned on regular round tracking.

**Comment by Tarmslitaren** [comment] 2023-12-21 19:02
I cannot reproduce. Did you tap the '1' section by mistake? Or do you have an earlier version?

**Comment by Tarmslitaren** [comment] 2024-09-03 07:43
No reproduction, closing.

**Closed** 2024-09-03 07:42 UTC
