### ISSUE TITLE
v1.6.0 on iPad characters/monsters disappear when zoomed out for multiple columns

### ISSUE THREAD

**Issue by christyray** [Tarmslitaren/FrosthavenAssistant#68] opened 2023-01-28 22:55 UTC
Hello! First of all, thank you for the app! It's been hugely helpful, and we wouldn't play without it.

I just updated to v1.6.0 on my iPad, and it doesn't display anything in the main list - no characters or monsters. Everything was working as expected before I updated versions, so I believe it's related to something in the update. 

If I select a scenario, the bottom bar updates with the scenario name and number, but no monsters appear. If I try to remove characters or monsters, it does show the monsters in the list of ones that can be removed. If I add characters or monsters, they don't appear in the main list either. 

I can still draw cards from the monster deck and make elements available. Changing the zoom level of the app bar/main list does change the size of the elements that are present, but it doesn't fix the missing characters/monsters. 

Older iPad Pro, running iOS 15.6.1, and I'm using local features only, not hosting a server. 

EDIT: Well, of course as soon as I hit post, we figured out that if we zoomed in more on the main list, the characters and monsters popped back in. It looks like the zooming out to make two columns appear isn't working and everything just disappears, but if we zoom in enough to make everything a single column, all of the characters and monsters show back up.

**Comment by Tarmslitaren** [comment] 2023-01-29 05:48
thanks for reporting. this seems to have broken with the new flutter update. ( been ignoring an exception when you have 2 lists but one of the lists is empty )

**Comment by Lurkars** [comment] 2023-01-29 15:29
Can confirm on Android (1.6.1) that zooming impact shown figures in 2-column mode.

**Comment by Tarmslitaren** [comment] 2023-01-31 12:31
the algorithm to decide what goes in first column vs the second is not entirely exact, that's why you can have these corner cases where you need to scroll to see one item even if there's room in the second column. As you can see in the video Lurkars posted.

I'll look over that separate issue, but it's low priority in my mind.

**Comment by Lurkars** [comment] 2023-01-31 13:00
Maybe it's not clear in the video, but the characters DISAPPEAR, they are not switching columns!

[target.webm](https://user-images.githubusercontent.com/2760570/215766588-2613b82d-98af-40cf-9623-6ebab6058a24.webm)

**Comment by Tarmslitaren** [comment] 2023-01-31 13:09
Unless I'm mistaken, if you scroll you will find they are at the bottom of
the left list, just out of view. Not a great user experience for sure but
not exactly critical.

There is a worse situation I just found,where if you have few enough items
in the list, and play a frosthaven scenario, the loot deck can cover
important ui. I should add extra scrolling for this situation as well. I
did add extra scrolling space to account for this, but forgot about that
particular 2 columns usecase.

**Comment by Lurkars** [comment] 2023-01-31 13:11
No, that's why I scrolled now explicit in the second video. Visual they are gone, I cannot see, interact or anything. Since it's related to zoom level, I shown on start, to flip screen: then suddenly characters are gone.

**Comment by Tarmslitaren** [comment] 2023-01-31 13:24
Ok. Color me surprised. Thanks for finding this. Seem to only happen when the characters are last in the list

**Comment by Lurkars** [comment] 2023-01-31 13:51
Yes you're right, I cannot reproduce with a monster sorted to the end!

**Comment by Tarmslitaren** [comment] 2023-02-03 07:08
1.6.2 fixed the second issue (last items in second column not showing in case there are more shorter items (characters) in second column. 

closing.

**Closed by Tarmslitaren** 2023-02-03 07:08 UTC
