### ISSUE TITLE
Android Performance/Memory Issue - v1.10.1

### ISSUE THREAD

**Issue by GameGhost** [Tarmslitaren/FrosthavenAssistant#243] opened 2024-12-22 14:39 UTC
Our setup:
* 1 laptop running the Windows version acting as "headless" server -- in another room, don't interact with it directly, just use it for server stability
* 3 devices on Android (various phones)
* 1 device on iOS
 
Updated the server to 1.10.1 (from the 1.10.1.0 version in the [10.0.0 release](https://github.com/Tarmslitaren/FrosthavenAssistant/releases/tag/v1.10.0)).
Then had all the devices update as well through the Play and Apple stores.

On at least 2 of the android devices we experienced significant performance issues not encountered on previous versions
* Laggy input -- sometimes up to 1 second delay between input and response, such as opening character or enemy panels
* Several crashes -- the app would lock up and then close or need to be restarted; once device encountered this multiple times, and another only once
* High power use -- one of the devices, the one that experienced multiple crashes, used a lot more battery during the session than normal and got significantly warm to the touch; this device is frequently used for other games and does not experience this behaviour in other apps or games

If there are ways to provide produce log files, or if other details are required, I would be happy to provide them.

**Comment by Tarmslitaren** [comment] 2024-12-22 16:05
Thanks for bringing this to my attention. It seems there's some issue with the latest Flutter framework. Can you confirm that this issue is only present for android?

**Comment by Tarmslitaren** [comment] 2024-12-22 19:42
made a hot fix for this. please notify if some part of the issue is still present. At least the performance is better now on my device.

**Closed by Tarmslitaren** 2024-12-22 19:42 UTC

**Comment by GameGhost** [comment] 2024-12-22 20:27
Wow, thanks for the quick fix!
It'll be a week or two before we get to play again, but we'll keep an eye on it.

But it was definitely affecting only android devices.
The iOS device was working better than ever (no disconnections from server, yay!).
The Windows version was fine for memory when I closed it.
