### ISSUE TITLE
Windows host doesn't allow iOS device to connect.  Android user changes were not coming through.

### ISSUE THREAD

**Issue by retupmoc258** [Tarmslitaren/FrosthavenAssistant#18] opened 2022-12-01 00:34 UTC
I had several issues with trying to use this app.  I had a Windows machine as a host and I tried to have both Android and iOS devices connect as clients.   No matter what I did, the iOS device would not connect to my host machine.  

In addition, after a few minutes of trying to use the app, the Android users would try to make changes and it would say that there was some kind of mismatch and it wouldn't update anything they did.  I may be able to recreate it.  All of us had the newest version (11/28/22).

**Comment by Tarmslitaren** [comment] 2022-12-01 07:00
The type of device shouldn't matter. 

For the mismatch problem, it means that the device somehow got disconnected and so is missing game state updates, so it's not allowed to update state immediately, but it should get the latest state at that time so trying again after getting that message should work.

You could try to switch device is host to the ios device see if it can create a server. It shouldn't matter though, unless a device is prone to disconnect. 

Not being able to connect at all, I can't say the exact reason (if you can catch what error message you get?)

In general:
1. make sure you are on the same wifi
2. connect to the servers local ip address (192.168.something.something)

I will examine ways to make improvements to the connection.

**Comment by retupmoc258** [comment] 2022-12-01 14:58
When the mismatch error would happen, our phones did not update with the
information on the Windows device. Trying again to change things just
reproduced the mismatch error.

We tried making the iOS device the host, and one of us was able to connect
to him. But given the mismatch errors, we didn't think using him as the
host would work any better. We tried the same connection information as we
did for the Android devices, but it wouldn't work. We even had him delete
and add the IP address again, verified he was up to date, and everything
else we could think of. We even turned off X-haven Assistant, then turned
it back on. But he still wasn't able to connect to my Windows computer, and
the errors with our other devices continued.

In total, with all of our devices losing connection frequently, the
mismatch errors that weren't resolving, and him unable to connect, we
finally stopped trying to use it. I think my phone even started to assume
that the Internet wasn't working because it had so many issues connecting
to this server and it switched to cell data on me at one point.

I can try again to see the error that pops up. But it does appear that each
time it pops up that there's a new port number associated with the IP
address--always different and not the same as the one we enter (e.g.
192.168.0.12:53632). When my phone first connected, it register as port
4567 (or whatever it is), but all the rest showed up on a different, random
port number. When my phone reconnected later, it was also on a random port
number. So maybe that has something to do with it?

Yes, we were on the same WiFi, and the same access point (I have 2.4GHz and
5GHz connections, but we were all on the 2.4GHz connection). We all typed
in the same IP address and port, but it wouldn't work for the iOS person.

It will be a while before I can test it again with more than my phone,
which is not the iOS device. I'll let you know if I find anything.

**Comment by Tarmslitaren** [comment] 2022-12-02 13:33
This might be a shot in the dark, but if you are on a non home wifi your firewall might want to disable incoming traffic unless you set a rule to let the port through. On the other hand it would be strange if this affects only ios device and not android.

**Comment by retupmoc258** [comment] 2022-12-02 14:39
It was my home WiFi network. I made sure the firewall on the conputer
didn't block the app (which was necessary to connect with the Android
devices).

I'll see what I can figure out next time I use it.

**Comment by wonderplayer** [comment] 2022-12-27 07:48
I can confirm that issues with index mismatch is present. Used Andoid phone as host with iOS and Android as clients. About every round we had to re-start the server to fix mismatch.
Maybe introducing different sync approach would be much safer than trying to correct connection issues? Like in commits. Always before push do pull from server to get latest changes, update and then push.
I will also try to look at this 😉

And thank you very, very much for this app! I lost all hope when switched from Android to iOS! Connection issue is minor compared to manual management of combat 🤣

**Comment by Tarmslitaren** [comment] 2022-12-27 07:58
Sorry for the connectivity issues. I'll be working on those. The type of
device shouldn't matter.

When it says you have a index mismatch, then you will get an updated state
from the server. since it's too complicated to tell if the action you were
planning to take is valid or desired in the new state, I opted not to
automatically apply it but let it be a user choice, so after a mismatch,
just try the action again and it should work, barring any other connection
issues.

**Comment by wonderplayer** [comment] 2022-12-27 08:03
Unfortunately that didn’t happen for me 😔
When index mismatch was encountered, clients were disconnected from host and could not reconnect to it unless host restarted the server.

**Comment by gdapchan** [comment] 2023-01-03 08:44
I have the index mismatch behavior regularly running the server on a Windows computer.  Restarting the server allows clients to connect again. Affects both IOS and Android clients.

**Comment by Tarmslitaren** [comment] 2023-01-14 23:51
these issues should be mostly alleviated with the last version: a bug closing connection instantly when reconnecting was fixed.

**Closed by Tarmslitaren** 2023-01-14 23:51 UTC
